#! /bin/bash

. /usr/lib/network/globals
. "$subr_dir/ip"

interface="$1"
ssid="$2"
profile="$3"
action="$4"


# Is it possible that we don't get a profile?!
[[ "$profile" ]] && load_profile "$profile"

case $action in
  CONNECT)
    if [[ -z $profile ]]; then
        if [[ -x "$profile_dir/interfaces/$interface" ]]; then
            source "$profile_dir/interfaces/$interface"
        fi
            if [ dhclient = "$(which_dhcp)" ]; then
                dhclient -q -r "$DhclientOptions" "$interface"
            else
                dhcpcd -qL -t "${TimeoutDHCP:-10}" "$DhcpcdOptions" -K "$interface"
            fi
        exit $?
    fi

    DhcpcdOptions+=" -K"
    DhclientOptions+=" -r"

    ip_set || exit 1
    [[ $var ]] && bash -c "$ExecUpPost" || netctl-auto stop "$interface"
    exit 1 
  ;;
  DISCONNECT)
      if [[ -z "$profile" ]]; then
        if [ dhclient = "$(which_dhcp)" ]; then
            dhclient -x "$interface"
        else
            dhcpcd -k "$interface"
        fi
        exit $?
    fi
    [[ $var ]] && bash -c "$ExecDownPre" || exit 1
    ip_unset
  ;;
  LOST|REESTABLISHED)
    # Not handled.
    exit 0
  ;;
  *)
    # Everything else.
    exit 1
  ;;
esac


# vim: ft=sh ts=4 et sw=4:
