#! /bin/bash

. /usr/lib/network/globals
. "$subr_dir/ip"

interface=$1
# ssid="$2"
profile=$3
action=$4

# Is it possible that we don't get a profile?!
[[ $profile && load_profile $profile ]] || exit 1

case "$action" in
    CONNECT)
        if [[ -z $profile ]]; then
            if [[ -x $profile_dir/interfaces/$interface ]]; then
                source $profile_dir/interfaces/$interface
            fi
            if [[ $which_dhcp = dhclient ]]; then
                dhclient -q -r "$DhclientOptions" "$interface"
            else
                dhcpcd -qL -t "${TimeoutDHCP:-10}" "$DhcpcdOptions" -K "$interface"
            fi
            exit $?
        fi

        DhcpcdOptions+=" -K"
        DhclientOptions+=" -r"

        ip_set || exit 1
        if ! "${ExecUpPost[@]}" &>/dev/null; then
            # Failing ExecUpPost will take the connection down
            netctl-auto stop "$interface"
            exit 1
        fi
        ;;
    DISCONNECT)
        if [[ -z $profile ]]; then
            if "$which_dhcp" = dhclient; then
                dhclient -x "$interface"
            else
                dhcpcd -k "$interface"
            fi
            exit $?
        fi
        "${ExecDownPre[@]}" &>/dev/null || exit 1
        ip_unset
        ;;
    LOST|REESTABLISHED)
        # Not handled.
        exit 0
        ;;
    *) # Everything else.
        exit 1
        ;;
esac


# vim: ft=sh ts=4 et sw=4:
